<?php
/*
 * Central API endpoint for Kilburn Klues.
 * Replaces Flask's app.py with PHP that works natively on the uni web server.
 *
 * The uni server (web.cs.manchester.ac.uk) runs PHP out of the box,
 * so no Python / Flask process is needed.
 *
 * Usage (all return JSON):
 *   api.php?action=guide_images            – guide / quiz images (optional &tag=)
 *   api.php?action=guide_tags              – available filter tags
 *   api.php?action=start_game              – shuffle questions, start session, return first Q
 *   api.php?action=get_question            – current question from session
 *   api.php?action=submit_answer           – POST JSON {"answer":"A"} or form data
 *   api.php?action=get_results             – final score (clears session)
 *   api.php?action=sync_tags               – admin: build labels from filenames
 */

session_start();
header('Content-Type: application/json');

/* ── Database credentials ────────────────────────────────────────────────────
 * config.inc.php is auto-generated by the uni web server when published.
 * It provides: $database_host, $database_user, $database_pass,
 *              $database_name, $group_dbnames (array).
 * See: https://wiki.cs.manchester.ac.uk/index.php/Web_Dashboard/Connecting_to_MySQL
 * ──────────────────────────────────────────────────────────────────────────── */

require_once('config.inc.php');

/* Connect to the group database (2025_comp10120_x16) */
$conn = new mysqli();
$conn->options(MYSQLI_OPT_CONNECT_TIMEOUT, 5);
$conn->real_connect($database_host, $database_user, $database_pass, $group_dbnames[0]);

if ($conn->connect_error) {
    http_response_code(500);
    echo json_encode(['error' => 'Database connection failed']);
    exit;
}

/* ── Route to the correct handler ───────────────────────────────────────────── */

$action = isset($_GET['action']) ? $_GET['action'] : '';

switch ($action) {
    case 'guide_images':  guideImages($conn);  break;
    case 'guide_tags':    guideTags($conn);    break;
    case 'start_game':    startGame($conn);    break;
    case 'get_question':  getQuestion($conn);  break;
    case 'submit_answer': submitAnswer($conn); break;
    case 'get_results':   getResults();        break;
    case 'sync_tags':        syncTags($conn);        break;
    case 'get_total_score': getTotalScore($conn);  break;
    case 'add_score':       addScore($conn);       break;
    case 'get_leaderboard':   getLeaderboard($conn);  break;
    case 'get_score_history': getScoreHistory($conn); break;
    default:
        echo json_encode(['error' => 'Unknown action: ' . $action]);
}

$conn->close();
exit;

/* ══════════════════════════════════════════════════════════════════════════════
 *  GUIDE
 * ══════════════════════════════════════════════════════════════════════════════ */

function guideImages($conn) {
    $tag = isset($_GET['tag']) ? trim($_GET['tag']) : '';

    if ($tag !== '') {
        $stmt = $conn->prepare(
            "SELECT q.* FROM quiz_questions q
             JOIN question_labels ql ON q.id = ql.question_id
             JOIN labels l ON l.id = ql.label_id
             WHERE l.name = ?"
        );
        $stmt->bind_param('s', $tag);
        $stmt->execute();
        $result = $stmt->get_result();
    } else {
        $result = $conn->query('SELECT * FROM quiz_questions');
    }

    $rows = [];
    while ($row = $result->fetch_assoc()) {
        // The DB stores full paths; the front-end only needs the filename
        $row['image_file'] = basename($row['image_url']);
        $rows[] = $row;
    }

    echo json_encode($rows);
}

function guideTags($conn) {
    $result = $conn->query('SELECT name FROM labels ORDER BY name');
    $tags = [];
    while ($row = $result->fetch_assoc()) {
        $tags[] = $row;
    }
    echo json_encode($tags);
}

/* ══════════════════════════════════════════════════════════════════════════════
 *  GAME
 * ══════════════════════════════════════════════════════════════════════════════ */

function startGame($conn) {
    $result = $conn->query('SELECT id, question_type, score FROM quiz_questions');
    $ids = [];
    $maxById = [];
    while ($row = $result->fetch_assoc()) {
        $qid = (int)$row['id'];
        $ids[] = $qid;

        $qType = isset($row['question_type']) ? $row['question_type'] : 'mcq';
        if ($qType === 'map') {
            $maxById[$qid] = $row['score'] ? (int)$row['score'] : 10;
        } else {
            // MCQ remains binary-scored in submitAnswer.
            $maxById[$qid] = 1;
        }
    }

    if (empty($ids)) {
        echo json_encode(['error' => 'No questions found in the database']);
        return;
    }

    shuffle($ids);
    $_SESSION['question_ids']  = $ids;
    $_SESSION['current_index'] = 0;
    $_SESSION['score']         = 0;
    $_SESSION['max_score']     = 0;

    foreach ($ids as $qid) {
        $_SESSION['max_score'] += isset($maxById[$qid]) ? (int)$maxById[$qid] : 1;
    }

    sendCurrentQuestion($conn);
}

function getQuestion($conn) {
    if (!isset($_SESSION['question_ids'])) {
        echo json_encode(['error' => 'No game in progress', 'redirect' => true]);
        return;
    }
    sendCurrentQuestion($conn);
}

function sendCurrentQuestion($conn) {
    $idx   = $_SESSION['current_index'];
    $ids   = $_SESSION['question_ids'];
    $total = count($ids);

    if ($idx >= $total) {
        echo json_encode([
            'game_over' => true,
            'score'     => $_SESSION['score'],
            'total'     => $total
        ]);
        return;
    }

    $qid  = $ids[$idx];
    $stmt = $conn->prepare('SELECT * FROM quiz_questions WHERE id = ?');
    $stmt->bind_param('i', $qid);
    $stmt->execute();
    $q = $stmt->get_result()->fetch_assoc();

    if ($q) {
        $q['image_file']     = basename($q['image_url']);
        $q['floorplan_file'] = $q['floorplan_url'] ? basename($q['floorplan_url']) : null;
        // Never expose the correct location before the user answers
        unset($q['correct_x'], $q['correct_y']);
    }

    echo json_encode([
        'question'      => $q,
        'current_index' => $idx,
        'total'         => $total,
        'score'         => $_SESSION['score']
    ]);
}

function submitAnswer($conn) {
    if (!isset($_SESSION['question_ids'])) {
        echo json_encode(['error' => 'No game in progress']);
        return;
    }

    $input = json_decode(file_get_contents('php://input'), true);

    $idx = $_SESSION['current_index'];
    $ids = $_SESSION['question_ids'];
    $qid = $ids[$idx];

    $stmt = $conn->prepare(
        'SELECT question_type, correct_answer, correct_x, correct_y, score FROM quiz_questions WHERE id = ?'
    );
    $stmt->bind_param('i', $qid);
    $stmt->execute();
    $row = $stmt->get_result()->fetch_assoc();

    $questionType = isset($row['question_type']) ? $row['question_type'] : 'mcq';

    if ($questionType === 'map') {
        $gx       = ($input && isset($input['x'])) ? (float)$input['x'] : 0;
        $gy       = ($input && isset($input['y'])) ? (float)$input['y'] : 0;
        $cx       = (float)$row['correct_x'];
        $cy       = (float)$row['correct_y'];
        // Euclidean distance in percentage units (0–100 space)
        $distance = sqrt(($gx - $cx) ** 2 + ($gy - $cy) ** 2);
        $maxScore = $row['score'] ? (int)$row['score'] : 10;
        // Full points within 2%, zero at 30%, linear between
        $points   = (int)round($maxScore * max(0, min(1, (30 - $distance) / 28)));
        $_SESSION['score'] += $points;
        $_SESSION['current_index']++;
        $gameOver = ($_SESSION['current_index'] >= count($ids));

        echo json_encode([
            'question_type' => 'map',
            'correct_x'     => $cx,
            'correct_y'     => $cy,
            'distance'      => round($distance, 1),
            'points_earned' => $points,
            'max_score'     => $maxScore,
            'game_over'     => $gameOver,
            'score'         => $_SESSION['score'],
            'current_index' => $_SESSION['current_index'],
            'total'         => count($ids)
        ]);
    } else {
        /* MCQ — original logic */
        $answer = '';
        if ($input && isset($input['answer'])) {
            $answer = $input['answer'];
        } elseif (isset($_POST['answer'])) {
            $answer = $_POST['answer'];
        } elseif (isset($_GET['answer'])) {
            $answer = $_GET['answer'];
        }

        $isCorrect = ($answer === $row['correct_answer']);
        if ($isCorrect) {
            $_SESSION['score']++;
        }
        $_SESSION['current_index']++;
        $gameOver = ($_SESSION['current_index'] >= count($ids));

        echo json_encode([
            'correct'        => $isCorrect,
            'correct_answer' => $row['correct_answer'],
            'game_over'      => $gameOver,
            'score'          => $_SESSION['score'],
            'current_index'  => $_SESSION['current_index'],
            'total'          => count($ids)
        ]);
    }
}



function getResults() {
    $score = isset($_SESSION['score'])        ? $_SESSION['score']                    : 0;
    $total = isset($_SESSION['max_score'])    ? (int)$_SESSION['max_score']
        : (isset($_SESSION['question_ids']) ? count($_SESSION['question_ids']) : 0);

    /* Clear game state so the next visit starts fresh */
    unset($_SESSION['question_ids'], $_SESSION['current_index'], $_SESSION['score'], $_SESSION['max_score']);

    echo json_encode(['score' => $score, 'total' => $total]);
}

/* ══════════════════════════════════════════════════════════════════════════════
 *  ADMIN – Sync Tags (run once in browser, same logic as Flask /admin/sync)
 * ══════════════════════════════════════════════════════════════════════════════ */

function syncTags($conn) {
    $result = $conn->query('SELECT id, image_url FROM quiz_questions');
    $count  = 0;

    while ($row = $result->fetch_assoc()) {
        if (!$row['image_url']) continue;

        $filename = basename($row['image_url']);
        $clean    = pathinfo($filename, PATHINFO_FILENAME);   // e.g. "Lab2.25_Two_Easy"
        $parts    = explode('_', $clean);
        array_shift($parts);                                  // drop the name part

        foreach ($parts as $tag) {
            $tag = ucfirst(strtolower(trim($tag)));
            if ($tag === '') continue;

            $stmt = $conn->prepare('INSERT IGNORE INTO labels (name) VALUES (?)');
            $stmt->bind_param('s', $tag);
            $stmt->execute();

            $stmt2 = $conn->prepare('SELECT id FROM labels WHERE name = ?');
            $stmt2->bind_param('s', $tag);
            $stmt2->execute();
            $labelId = $stmt2->get_result()->fetch_assoc()['id'];

            $stmt3 = $conn->prepare('INSERT IGNORE INTO question_labels (question_id, label_id) VALUES (?, ?)');
            $stmt3->bind_param('ii', $row['id'], $labelId);
            $stmt3->execute();
            $count++;
        }
    }

    echo json_encode(['message' => "Synced tags. $count tag-links processed."]);
}

/* ══════════════════════════════════════════════════════════════════════════════
 *  USER SCORES
 * ══════════════════════════════════════════════════════════════════════════════ */

function ensureUserScoresTable($conn) {
    $conn->query("
        CREATE TABLE IF NOT EXISTS user_scores (
            google_id   VARCHAR(255) PRIMARY KEY,
            email       VARCHAR(255),
            name        VARCHAR(255),
            total_score INT DEFAULT 0
        )
    ");

    // Supports fast ORDER BY total_score DESC LIMIT 10 leaderboard queries.
    $idxResult = $conn->query("SHOW INDEX FROM user_scores WHERE Key_name = 'idx_user_scores_total_score'");
    if ($idxResult && $idxResult->num_rows === 0) {
        $conn->query('CREATE INDEX idx_user_scores_total_score ON user_scores (total_score)');
    }

    $conn->query("
        CREATE TABLE IF NOT EXISTS score_history (
            id        INT AUTO_INCREMENT PRIMARY KEY,
            google_id VARCHAR(255) NOT NULL,
            score     INT NOT NULL,
            played_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_score_history_google_id (google_id)
        )
    ");
}

function getTotalScore($conn) {
    $googleId = isset($_GET['google_id']) ? trim($_GET['google_id']) : '';
    if ($googleId === '') {
        echo json_encode(['total_score' => 0]);
        return;
    }

    ensureUserScoresTable($conn);
    $stmt = $conn->prepare('SELECT total_score FROM user_scores WHERE google_id = ?');
    $stmt->bind_param('s', $googleId);
    $stmt->execute();
    $row = $stmt->get_result()->fetch_assoc();
    echo json_encode(['total_score' => $row ? (int)$row['total_score'] : 0]);
}

function addScore($conn) {
    $input = json_decode(file_get_contents('php://input'), true);
    $googleId = isset($input['google_id']) ? trim($input['google_id']) : '';
    if ($googleId === '') {
        http_response_code(400);
        echo json_encode(['error' => 'google_id required']);
        return;
    }

    $email = isset($input['email']) ? $input['email'] : '';
    $name  = isset($input['name'])  ? $input['name']  : '';
    $score = isset($input['score']) ? (int)$input['score'] : 0;

    ensureUserScoresTable($conn);

    $stmt = $conn->prepare("
        INSERT INTO user_scores (google_id, email, name, total_score)
        VALUES (?, ?, ?, ?)
        ON DUPLICATE KEY UPDATE
            email = VALUES(email),
            name  = VALUES(name),
            total_score = total_score + VALUES(total_score)
    ");
    $stmt->bind_param('sssi', $googleId, $email, $name, $score);
    $stmt->execute();

    $stmtH = $conn->prepare('INSERT INTO score_history (google_id, score) VALUES (?, ?)');
    $stmtH->bind_param('si', $googleId, $score);
    $stmtH->execute();

    $stmt2 = $conn->prepare('SELECT total_score FROM user_scores WHERE google_id = ?');
    $stmt2->bind_param('s', $googleId);
    $stmt2->execute();
    $row = $stmt2->get_result()->fetch_assoc();
    echo json_encode(['total_score' => $row ? (int)$row['total_score'] : $score]);
}

function getScoreHistory($conn) {
    $googleId = isset($_GET['google_id']) ? trim($_GET['google_id']) : '';
    if ($googleId === '') {
        echo json_encode(['scores' => [], 'best_score' => 0]);
        return;
    }

    ensureUserScoresTable($conn);

    $stmt = $conn->prepare(
        'SELECT score, played_at FROM score_history WHERE google_id = ? ORDER BY played_at DESC LIMIT 10'
    );
    $stmt->bind_param('s', $googleId);
    $stmt->execute();
    $result = $stmt->get_result();
    $scores = [];
    while ($row = $result->fetch_assoc()) {
        $scores[] = ['score' => (int)$row['score'], 'played_at' => $row['played_at']];
    }

    $stmt2 = $conn->prepare(
        'SELECT COALESCE(MAX(score), 0) AS best_score FROM score_history WHERE google_id = ?'
    );
    $stmt2->bind_param('s', $googleId);
    $stmt2->execute();
    $best = $stmt2->get_result()->fetch_assoc();

    echo json_encode(['scores' => $scores, 'best_score' => $best ? (int)$best['best_score'] : 0]);
}

function getLeaderboard($conn) {
    ensureUserScoresTable($conn);

    $result = $conn->query(
        "SELECT
            COALESCE(NULLIF(TRIM(name), ''), 'Anonymous') AS name,
            total_score
         FROM user_scores
         ORDER BY total_score DESC, name ASC
         LIMIT 10"
    );

    $leaderboard = [['name' => 'KilburnDevGroup', 'total_score' => 9999999999]];
    if ($result) {
        while ($row = $result->fetch_assoc()) {
            $leaderboard[] = [
                'name' => $row['name'],
                'total_score' => (int)$row['total_score']
            ];
        }
    }

    echo json_encode(['leaderboard' => $leaderboard]);
}
