<?php
/*
 * API endpoint: returns guide image data from the MySQL database as JSON.
 *
 * The uni web server (web.cs.manchester.ac.uk) runs PHP natively,
 * so this works without needing Flask or any Python process running.
 *
 * URL: https://web.cs.manchester.ac.uk/z79733my/kilburnklues/api/guide_images.php
 */

header('Content-Type: application/json');

/* config.inc.php is auto-generated by the uni web server when published.
 * It provides: $database_host, $database_user, $database_pass,
 *              $database_name, $group_dbnames (array). */
require_once('config.inc.php');

/* Connect to the group database (2025_comp10120_x16) */
$conn = new mysqli($database_host, $database_user, $database_pass, $group_dbnames[0]);

if ($conn->connect_error) {
    http_response_code(500);
    echo json_encode(['error' => 'Database connection failed']);
    exit;
}

$result = $conn->query('SELECT * FROM quiz_questions ORDER BY id');

$images = [];
while ($row = $result->fetch_assoc()) {
    $row['image_file'] = basename($row['image_url']);
    $images[] = $row;
}

$conn->close();

echo json_encode($images);
